import type { Block } from "./guides-data";

export interface BlogPost {
  slug: string;
  category: string;
  categoryColor: string;
  title: string;
  excerpt: string;
  readTime: string;
  publishedDate: string;
  author: string;
  authorRole: string;
  coverGradient: string;
  blocks: Block[];
  relatedSlugs: string[];
}

export const blogPosts: BlogPost[] = [
  // ─── 1 ───────────────────────────────────────────────────────────────────
  {
    slug: "esg-ratings-divergence-2026",
    category: "Research",
    categoryColor: "bg-violet-100 text-violet-700",
    title: "ESG Ratings Divergence Explained: Why Scores Differ 40+ Points Across Providers",
    excerpt: "Two equally rigorous analysts can score the same company 40 points apart. This is not a bug — it is the defining structural challenge of ESG data. Learn why ESG ratings diverge and how to navigate multi-provider analysis.",
    readTime: "11 min read",
    publishedDate: "April 2026",
    author: "OpenESG Research Team",
    authorRole: "Data & Methodology",
    coverGradient: "from-emerald-600 to-teal-800",
    relatedSlugs: ["esg-ratings-backlash", "water-risk-underpriced"],
    blocks: [
      { type: "h2", text: "The divergence problem" },
      { type: "p", text: "In 2022, a study by MIT Sloan researchers found that the average correlation between the six major ESG rating providers was just 0.54 — compared to 0.99 for credit ratings from Moody's and S&P. For investors who grew up trusting credit ratings as near-objective facts, this gap is disorienting. A company like Tesla carries an ESG score ranging from 14 (MSCI) to 78 (FTSE Russell) depending on which provider you consult." },
      { type: "p", text: "This is not primarily a data quality problem. It is a conceptual disagreement problem. Before any data is collected, rating providers must decide: What counts as an ESG factor? How much does each factor matter? How do you handle missing disclosures? Every one of these choices creates legitimate divergence." },
      { type: "callout", variant: "key", title: "The core insight", text: "ESG scores are not measurements — they are opinions. Just as two portfolio managers can produce different fair-value estimates from identical financial statements, two ESG analysts can rationally produce very different composite scores from identical sustainability data." },
      { type: "h2", text: "Three structural causes of divergence" },
      { type: "h3", text: "1. Scope divergence — what is being measured" },
      { type: "p", text: "MSCI focuses primarily on financially material risks to the company. GRI focuses on the company's impact on the world. These are philosophically opposite starting points. A company with massive environmental impact but strong risk management scores well under MSCI and poorly under GRI. Neither rating is wrong — they answer different questions." },
      { type: "table", headers: ["Provider", "Primary lens", "Key inclusion choices"], rows: [
        ["MSCI", "Financial materiality to investors", "Industry-specific metrics, transition risk, controversy deductions"],
        ["Sustainalytics", "Unmanaged ESG risk exposure", "Risk exposure × management quality scoring"],
        ["FTSE Russell", "ESG exposure + management", "200+ indicators, equal sector weighting"],
        ["Bloomberg", "Disclosure quality proxy", "Scores penalise non-disclosure heavily"],
        ["ISS ESG", "Impact and best practice", "Long controversy tail, supply chain scope"],
        ["CDP", "Climate/water/forest disclosure", "Voluntary questionnaire — measures intent, not performance"],
      ]},
      { type: "h3", text: "2. Measurement divergence — how data is collected" },
      { type: "p", text: "Even when two providers agree on what to measure, they may disagree on the metric. Carbon intensity per revenue dollar and carbon intensity per employee capture the same underlying concern but can produce opposite conclusions for a capital-light software company versus a capital-heavy manufacturer. Providers also treat self-reported data, third-party audited data, and imputed estimates very differently." },
      { type: "h3", text: "3. Aggregation divergence — how factors are combined" },
      { type: "p", text: "Once individual metrics are collected, they must be combined into a score. Do you weight E, S, and G equally? Do you apply industry-specific weights? Do you use linear or percentile normalisation? Do controversies trigger deductions or separate overlays? Each of these aggregation decisions — invisible to the end user — can swing the final score significantly." },
      { type: "callout", variant: "warning", title: "The rater-shopping problem", text: "Companies have learned to optimise for the methodologies of their most important ratings customers. This creates a perverse incentive: rather than improving genuine sustainability performance, some companies improve disclosure quality and stakeholder communication targeted at specific provider methodologies. This is legal and common — but it widens the gap between ratings and reality." },
      { type: "h2", text: "A practical framework for multi-provider analysis" },
      { type: "p", text: "The answer is not to pick one provider and ignore the rest. It is to triangulate. When ratings converge across providers, confidence in the underlying signal is high. When they diverge sharply, that divergence itself is informative — it tells you a genuine debate exists about what matters for this company." },
      { type: "ol", items: [
        "Start with the consensus — average or median score across providers tells you the central tendency of market opinion",
        "Identify outliers — if one provider rates a company 30 points above average, find out why. The outlier methodology often reveals something the consensus misses",
        "Map divergence to business model — a logistics company rated differently on Scope 3 methodology is not the same problem as a bank rated differently on governance controversy treatment",
        "Prefer audit-verified disclosures — companies with third-party assured reports have smaller divergence across providers because imputed estimates are replaced by verified data",
        "Track stability over time — volatile scores often signal a company that is gaming disclosure rather than improving performance",
      ]},
      { type: "h2", text: "How OpenESG handles divergence" },
      { type: "p", text: "OpenESG uses a proprietary methodology that combines quantitative metrics from company filings and regulatory databases with qualitative assessment of disclosure quality and news-sourced controversy monitoring. Rather than hiding the uncertainty in a single number, we expose it — each score comes with a confidence band and a breakdown of which factors are driving the result." },
      { type: "p", text: "Our ESG Intelligence Engine, powered by Claude Sonnet, reads the latest company disclosures, regulatory filings, and news to flag discrepancies between stated commitments and observable actions. This is particularly valuable for catching the gap between what companies claim in sustainability reports and what appears in contemporaneous news coverage." },
      { type: "callout", variant: "tip", title: "How to use ESG scores effectively", text: "Use them as screening tools, not verdicts. An ESG score should prompt questions, not provide answers. When a score surprises you — high or low — that is the signal to dig deeper into the underlying data, not to accept the number at face value." },
    ],
  },
  // ─── 2 ───────────────────────────────────────────────────────────────────
  {
    slug: "carbon-credits-demystified",
    category: "Climate",
    categoryColor: "bg-emerald-100 text-emerald-700",
    title: "Carbon Credits Explained: Voluntary vs Compliance Markets — ESG Analyst's Guide",
    excerpt: "Companies are buying billions in carbon credits to claim net-zero. Some credits are genuine. Many are not. Here is what every ESG analyst needs to know about carbon credit quality, additionality, and net-zero claim integrity.",
    readTime: "13 min read",
    publishedDate: "April 2026",
    author: "OpenESG Research Team",
    authorRole: "Climate Analysis",
    coverGradient: "from-emerald-600 to-teal-800",
    relatedSlugs: ["esg-ratings-divergence-2026", "eu-taxonomy-guide"],
    blocks: [
      { type: "h2", text: "What is a carbon credit?" },
      { type: "p", text: "A carbon credit represents one tonne of CO₂ equivalent that has either been prevented from entering the atmosphere or removed from it. When a company buys a credit and retires it, it is claiming that the tonne of CO₂ associated with that credit has been offset. The practical consequence is that the company can subtract one tonne from its reported emissions." },
      { type: "p", text: "This sounds straightforward. The problem is that the integrity of carbon credits varies enormously — from high-quality direct air capture credits backed by physical measurements to deeply questionable forestry credits based on unverifiable counterfactual baselines. An ESG analyst cannot treat all carbon credits as equivalent." },
      { type: "callout", variant: "warning", title: "The Verra crisis of 2023", text: "A 2023 Guardian/Zeit/SourceMaterial investigation found that over 90% of Verra's rainforest offset credits — the most widely used type — were 'phantom credits' that did not represent real carbon reductions. This triggered a collapse in voluntary carbon market prices and fundamentally damaged the credibility of offsetting as a net-zero strategy." },
      { type: "h2", text: "Compliance vs voluntary markets" },
      { type: "p", text: "There are two fundamentally different types of carbon markets, with very different quality characteristics." },
      { type: "table", headers: ["Dimension", "Compliance Market (ETS)", "Voluntary Market (VCM)"], rows: [
        ["Participation", "Mandatory — regulated entities must comply", "Voluntary — companies choose to participate"],
        ["Examples", "EU ETS, California Cap-and-Trade, UK ETS", "Gold Standard, Verra VCS, ACR, CAR"],
        ["Price range", "€50–€80/t CO₂ (EU ETS 2025)", "$2–$200+/t depending on project type"],
        ["Verification", "Government-mandated third-party audit", "Standard body verification (variable rigour)"],
        ["Integrity", "Generally high — legal penalties for fraud", "Variable — major fraud and quality issues documented"],
        ["Additionality", "Built into cap design", "Frequently contested — the core quality problem"],
      ]},
      { type: "h2", text: "The four quality tests for a carbon credit" },
      { type: "p", text: "When evaluating whether a company's carbon credit strategy represents genuine climate action or greenwashing, apply four tests to each credit type they purchase." },
      { type: "h3", text: "1. Additionality" },
      { type: "p", text: "Would the emission reduction have happened without the carbon finance? A hydropower project in a country with mandatory renewable energy targets is not additional — it would have been built regardless. An avoided deforestation project in a region with a functioning economy but optional forest protection is more plausibly additional." },
      { type: "h3", text: "2. Permanence" },
      { type: "p", text: "Will the carbon storage last? Forestry projects are fundamentally at risk from wildfire, disease, drought, and policy change. The 2021 Bootleg Fire in Oregon burned through 1 million tonnes of forestry credits in weeks. Geological storage (CCS, DAC) offers permanence on century timescales. This is a genuine qualitative difference." },
      { type: "h3", text: "3. Measurability" },
      { type: "p", text: "Can the claimed reduction be verified against a credible baseline? The counterfactual problem — what would have happened without the project — is the hardest methodological challenge in carbon accounting. Satellite-monitored cookstove projects are more measurable than baseline deforestation rates in poorly governed forest regions." },
      { type: "h3", text: "4. No double counting" },
      { type: "p", text: "Has the same tonne been claimed by multiple parties? Under Article 6 of the Paris Agreement, host country Nationally Determined Contributions must make a Corresponding Adjustment when a credit is used by a company in another country. Many pre-2023 credits do not satisfy this requirement and are now considered non-Paris-aligned." },
      { type: "h2", text: "Credit types by quality tier" },
      { type: "table", headers: ["Credit Type", "Quality Tier", "Key Risk"], rows: [
        ["Direct Air Capture (DAC)", "Highest", "High cost ($200–$1000/t), limited scale"],
        ["Bioenergy + CCS (BECCS)", "High", "Land use, energy intensity"],
        ["Enhanced Rock Weathering", "Medium-High", "Permanence still under research"],
        ["Cookstoves / Clean energy", "Medium", "Baseline methodology concerns"],
        ["Reforestation (new planting)", "Medium", "Impermanence, time lag (decades to sequester)"],
        ["REDD+ (avoided deforestation)", "Low-Medium", "Additionality, leakage, baseline inflation"],
        ["Older renewable energy RECs", "Low", "Non-additional in most markets today"],
      ]},
      { type: "h2", text: "ESG analyst framework" },
      { type: "p", text: "When reviewing a company's net-zero claim that relies on carbon offsets, ask these questions in order:" },
      { type: "checklist", title: "Carbon credit quality checklist", items: [
        "What percentage of the net-zero claim is covered by actual emission reductions vs credits?",
        "What standard were the credits issued under (Gold Standard, Verra, ACR, compliance ETS)?",
        "What project types are being purchased — avoidance, reduction, or removal?",
        "Are the credits Paris-aligned with Corresponding Adjustments under Article 6?",
        "Are credits third-party audited by a recognised verifier?",
        "Is there a transition plan to phase out offsets as the company decarbonises operations?",
        "Are credit purchases disclosed at the vintage, project, and registry level?",
      ]},
      { type: "callout", variant: "info", title: "The VCMI Claims Code", text: "The Voluntary Carbon Markets Integrity Initiative (VCMI) published its Claims Code of Practice in 2023, which distinguishes between 'Core Carbon Claim,' 'Gold Carbon Claim,' and 'Platinum Carbon Claim' based on how much of the company's claimed offset is backed by high-integrity credits. Look for VCMI-aligned disclosures when assessing net-zero credibility." },
    ],
  },
  // ─── 3 ───────────────────────────────────────────────────────────────────
  {
    slug: "how-to-read-sustainability-report",
    category: "Practitioner",
    categoryColor: "bg-sky-100 text-sky-700",
    title: "How to Read a Corporate Sustainability Report: A 30-Minute Analyst Checklist",
    excerpt: "Sustainability reports are long, inconsistent, and full of carefully worded non-commitments. This step-by-step guide shows how to extract signal from the noise — covering assurance levels, absolute vs intensity metrics, base year manipulation, and greenwashing red flags.",
    readTime: "10 min read",
    publishedDate: "March 2026",
    author: "OpenESG Research Team",
    authorRole: "ESG Analysis",
    coverGradient: "from-sky-600 to-blue-800",
    relatedSlugs: ["social-washing-beyond-greenwashing", "esg-ratings-divergence-2026"],
    blocks: [
      { type: "h2", text: "The honest problem with sustainability reports" },
      { type: "p", text: "Sustainability reports are corporate marketing documents that happen to contain some data. They are written by communications and legal teams to maximise positive impression while minimising legal liability. The information is real — but framing, omission, and selective comparison do enormous work. A skilled analyst learns to distinguish what a company is saying from what the data actually shows." },
      { type: "callout", variant: "warning", title: "Start with scepticism, not hostility", text: "Treating every sustainability report as pure greenwashing is as analytically wrong as accepting it at face value. Most large companies are making genuine progress on some dimensions while lagging on others. Your job is to find out which is which." },
      { type: "h2", text: "Step 1: Read the auditor section first (5 minutes)" },
      { type: "p", text: "Before you read anything else, find the external assurance or audit section. This tells you immediately how much to trust the numbers. Three possible outcomes:" },
      { type: "ul", items: [
        "No third-party assurance: All numbers are self-reported. Treat them as directional estimates, not facts.",
        "Limited assurance: An auditor has reviewed key metrics for plausibility but not depth. Numbers are more reliable but not guaranteed accurate.",
        "Reasonable assurance: The highest standard — auditor has tested data against source evidence. These numbers can be used with similar confidence to audited financial data.",
      ]},
      { type: "p", text: "In 2025, approximately 60% of Fortune 500 sustainability reports had some form of third-party assurance. The trend is upward, driven by CSRD and SEC climate disclosure rules." },
      { type: "h2", text: "Step 2: Find the absolute numbers, ignore the relative ones (10 minutes)" },
      { type: "p", text: "Sustainability reports lead with intensity metrics — 'we reduced our emissions per unit of revenue by 28%.' This is almost always true and almost always misleading when the company is growing. Find the absolute emissions numbers (total Scope 1, Scope 2, Scope 3 in tonnes CO₂e). If they are not in the summary, search for the GRI or SASB index at the back." },
      { type: "p", text: "Apply the same logic to social metrics. '15% improvement in safety incidents' is meaningless without the baseline number and the absolute count. '15% improvement from 1,200 recordable incidents to 1,020' tells a very different story than '15% improvement from 8 incidents to 7.'" },
      { type: "callout", variant: "tip", title: "The 3-year trend test", text: "A single year of data tells you very little. Always look for three or more years of comparable data. A metric that improved for two years then plateaued, or that improved once then worsened, reveals the company's true trajectory more accurately than the headline year-over-year comparison." },
      { type: "h2", text: "Step 3: Check the base year and boundary scope (5 minutes)" },
      { type: "p", text: "The most common manipulation in sustainability reporting is base year selection. A company might choose a 2007 base year (a record high emissions year) rather than 2019 to maximise the appearance of progress. Similarly, companies frequently change their reporting boundary — if a major emitting subsidiary is sold, reported emissions fall without any genuine decarbonisation." },
      { type: "ul", items: [
        "Check whether the base year has been restated for acquisitions/disposals — restated is better",
        "Check whether Scope 3 is included and what categories are covered (most companies exclude some)",
        "Check whether the reporting boundary matches the financial consolidation boundary",
        "Check whether the comparison year is 2019 (pre-COVID) or 2020 (COVID distortion year)",
      ]},
      { type: "h2", text: "Step 4: Cross-reference the controversies (10 minutes)" },
      { type: "p", text: "Every major sustainability report has an 'Our challenges and controversies' section. Read it. Then search for the company name + '[biggest controversy keyword]' in news databases. The gap between what companies disclose and what is publicly known is where greenwashing risk lives. If a company is facing material ESG litigation, regulatory investigation, or activist shareholder campaigns, this should appear prominently in the report. If it does not, that is a red flag." },
      { type: "h2", text: "Step 5: Test the forward commitments against current trajectory (10 minutes)" },
      { type: "p", text: "Net-zero by 2050 commitments are only as credible as the near-term milestones backing them. A company that has committed to net-zero by 2050 but whose emissions have risen every year for five years is not credibly committed. Find the 2025 and 2030 interim targets. Check whether current performance is on track to meet them. If emissions need to fall 40% by 2030 and have fallen 6% in three years, the 2050 target is implausible." },
      { type: "checklist", title: "30-minute sustainability report quality checklist", items: [
        "Third-party assurance level noted (none / limited / reasonable)",
        "Absolute emissions trend for 3+ years found and recorded",
        "Base year validity checked — post-2015, no cherry-picked low-emission year",
        "Scope 3 coverage checked — is supply chain included?",
        "Boundary changes noted year-over-year",
        "Major controversies cross-referenced with external sources",
        "2025 and 2030 interim targets found",
        "Trajectory assessment: are they on track for interim targets?",
        "Offsetting strategy reviewed — quality and proportion of offsets vs reductions",
        "GRI or SASB content index found — confirms systematic disclosure",
      ]},
    ],
  },
  // ─── 4 ───────────────────────────────────────────────────────────────────
  {
    slug: "eu-taxonomy-guide",
    category: "Regulatory",
    categoryColor: "bg-sky-100 text-sky-700",
    title: "EU Taxonomy for Sustainable Activities Explained: The Green Finance Classification System",
    excerpt: "The EU Taxonomy is the world's first government-backed classification system for sustainable economic activities — the technical foundation beneath SFDR and CSRD. Essential reading for analysts working with European companies or EU-regulated funds.",
    readTime: "14 min read",
    publishedDate: "March 2026",
    author: "OpenESG Research Team",
    authorRole: "Regulatory Intelligence",
    coverGradient: "from-blue-600 to-indigo-800",
    relatedSlugs: ["carbon-credits-demystified", "tnfd-nature-framework"],
    blocks: [
      { type: "h2", text: "What the EU Taxonomy is — and is not" },
      { type: "p", text: "The EU Taxonomy Regulation (EU 2020/852) is a classification system that defines which economic activities qualify as 'environmentally sustainable.' It is not a rating system — it does not score companies. It is not a prohibition — it does not ban non-green activities. It is a definition: a standardised answer to the question 'what counts as green?' for the purposes of EU financial regulation." },
      { type: "p", text: "The Taxonomy is the technical foundation beneath SFDR and CSRD. When a fund manager says their Article 9 fund invests in 'Taxonomy-aligned activities,' or when a company discloses their 'Taxonomy-eligible revenue,' they are using this classification system as the reference standard." },
      { type: "callout", variant: "key", title: "Why it matters beyond the EU", text: "The EU Taxonomy is becoming a de facto global standard. The UK, Canada, Singapore, Japan, and several other jurisdictions have launched taxonomies modelled on the EU framework. If you understand the EU Taxonomy, you understand the template for global green finance classification." },
      { type: "h2", text: "The six environmental objectives" },
      { type: "p", text: "The Taxonomy covers six environmental objectives. An activity can qualify as sustainable by substantially contributing to at least one of these while not significantly harming any of the others (the DNSH test)." },
      { type: "ul", items: [
        "Climate change mitigation — reducing greenhouse gas emissions",
        "Climate change adaptation — reducing vulnerability to climate impacts",
        "Sustainable use and protection of water and marine resources",
        "Transition to a circular economy — reducing waste, extending product life",
        "Pollution prevention and control",
        "Protection and restoration of biodiversity and ecosystems",
      ]},
      { type: "p", text: "As of 2025, Delegated Acts covering climate change mitigation and adaptation are in force (since 2022). The remaining four environmental objectives were covered by the Environmental Delegated Act in 2023. The Social Taxonomy remains under development." },
      { type: "h2", text: "The four-gate test for Taxonomy alignment" },
      { type: "p", text: "For an economic activity to be classified as Taxonomy-aligned, it must pass four gates in sequence. Failing any gate disqualifies the activity." },
      { type: "table", headers: ["Gate", "Requirement", "Example"], rows: [
        ["1. Eligible activity", "Activity is listed in the Taxonomy", "Solar power generation ✓; tobacco farming ✗ (not listed)"],
        ["2. Substantial contribution", "Activity meets sector-specific technical screening criteria", "Solar PV must meet minimum efficiency thresholds"],
        ["3. Do No Significant Harm", "Activity does not significantly harm any of the other 5 objectives", "A wind farm that damages a protected marine habitat fails this gate"],
        ["4. Minimum social safeguards", "Company complies with OECD Guidelines, UN Guiding Principles, and ILO core labour standards", "A compliant solar developer in a jurisdiction with documented forced labour in supply chain may fail"],
      ]},
      { type: "h2", text: "Taxonomy disclosure requirements" },
      { type: "p", text: "Under CSRD and NFRD, large companies must disclose three Taxonomy KPIs for each objective:" },
      { type: "ul", items: [
        "Taxonomy-eligible revenue: Revenue from activities that could potentially qualify (regardless of whether they meet screening criteria)",
        "Taxonomy-aligned revenue: Revenue from activities that pass all four gates",
        "Taxonomy-eligible and aligned CapEx: Capital expenditure directed toward eligible and aligned activities",
        "Taxonomy-eligible and aligned OpEx: Operating expenditure related to eligible activities",
      ]},
      { type: "callout", variant: "info", title: "Eligible vs aligned — a critical distinction", text: "Many companies report high Taxonomy eligibility (activities that are listed) but low Taxonomy alignment (activities that actually meet screening criteria). A 75% eligible / 12% aligned disclosure tells a very different story than 75% eligible / 68% aligned. Always look at the alignment number, not the eligibility number, when assessing genuine green activity." },
      { type: "h2", text: "The controversial inclusions: gas and nuclear" },
      { type: "p", text: "The Complementary Climate Delegated Act (July 2022) controversially classified certain natural gas and nuclear energy activities as Taxonomy-aligned transition activities under strict conditions. Gas qualifies if it replaces coal, meets specific emission thresholds, and transitions to hydrogen by 2035. Nuclear qualifies if waste management plans are in place and sites meet environmental safety standards." },
      { type: "p", text: "These inclusions were politically contentious — France pushed for nuclear, Germany initially opposed gas. The compromise means Taxonomy-aligned disclosures from energy companies must be interpreted carefully, as they may include activities that are 'green by transition' rather than 'green by destination.'" },
      { type: "h2", text: "How to use Taxonomy disclosures in ESG analysis" },
      { type: "checklist", title: "Taxonomy analysis checklist", items: [
        "Find the Taxonomy table in the annual report (usually in the Non-Financial Statement or CSRD annex)",
        "Compare eligible vs aligned percentages — large gap signals aspirational rather than achieved green activity",
        "Check which objectives the company claims substantial contribution to",
        "Review DNSH disclosures — are they substantive or boilerplate?",
        "Check minimum social safeguards section for supply chain labour risk",
        "For financial companies: check the Green Asset Ratio (GAR) — proportion of loans/investments in Taxonomy-aligned activities",
        "Year-over-year trend: is alignment improving as CapEx is deployed?",
      ]},
    ],
  },
  // ─── 5 ───────────────────────────────────────────────────────────────────
  {
    slug: "tnfd-nature-framework",
    category: "Frameworks",
    categoryColor: "bg-teal-100 text-teal-700",
    title: "TNFD Explained: The Nature-Risk Disclosure Framework for ESG Reporting in 2026",
    excerpt: "Biodiversity and nature-related financial risks are the next frontier of ESG disclosure. The Taskforce on Nature-related Financial Disclosures (TNFD) framework is here — more complex than TCFD and rapidly approaching mandatory status. Here is what every ESG analyst needs to know.",
    readTime: "12 min read",
    publishedDate: "February 2026",
    author: "OpenESG Research Team",
    authorRole: "Frameworks & Standards",
    coverGradient: "from-teal-600 to-emerald-800",
    relatedSlugs: ["eu-taxonomy-guide", "water-risk-underpriced"],
    blocks: [
      { type: "h2", text: "What TNFD is and why it was created" },
      { type: "p", text: "The Taskforce on Nature-related Financial Disclosures (TNFD) was established in 2021 by 34 financial institutions and corporations, with backing from G7 governments, UNDP, UNEP FI, and WWF. Its mandate was explicit: do for biodiversity and nature what TCFD did for climate — create a voluntary, market-based disclosure framework that eventually becomes mandatory." },
      { type: "p", text: "The Kunming-Montreal Global Biodiversity Framework (2022) agreed by 196 countries includes Target 15, which explicitly calls for large companies and financial institutions to regularly disclose nature-related risks, dependencies, and impacts. TNFD is the voluntary implementation pathway for Target 15. By 2030, nature disclosure is expected to be mandatory for large companies in most major jurisdictions." },
      { type: "callout", variant: "key", title: "The scale of nature risk", text: "The World Economic Forum estimates that $44 trillion of economic value — more than half of global GDP — is moderately or highly dependent on nature and ecosystem services. Yet until TNFD, companies had no standardised way to assess or disclose this dependency. Climate risk quantification is mature by comparison." },
      { type: "h2", text: "TNFD structure: familiar but more complex than TCFD" },
      { type: "p", text: "TNFD follows TCFD's four-pillar structure: Governance, Strategy, Risk Management, and Metrics & Targets. This was deliberate — building on TCFD's institutional credibility and established corporate disclosure processes. But the underlying science is considerably more complex." },
      { type: "table", headers: ["Pillar", "TCFD equivalent", "What TNFD adds"], rows: [
        ["Governance", "Board oversight of climate risks", "Board oversight of nature risks and dependencies"],
        ["Strategy", "Climate scenario analysis", "Location-specific nature assessment (LEAP approach)"],
        ["Risk & Impact Management", "Climate risk identification", "Four capitals: natural, social, human, financial"],
        ["Metrics & Targets", "GHG emissions, climate scenarios", "14 core metrics across impacts, dependencies, and state of nature"],
      ]},
      { type: "h2", text: "The LEAP approach: location is everything" },
      { type: "p", text: "The most distinctive element of TNFD relative to TCFD is its location-specificity. Climate change is essentially a global average problem — a tonne of CO₂ emitted anywhere has the same warming effect. Nature is completely different: the biodiversity value of a hectare of land in an Amazon hotspot is vastly different from a hectare in an already-degraded industrial zone. TNFD's LEAP methodology requires companies to assess nature risks and impacts at the specific location where they operate and source." },
      { type: "ul", items: [
        "L — Locate: Map your interface with nature by identifying sites of operation and priority supply chain locations on biodiversity maps",
        "E — Evaluate: Assess dependencies and impacts on nature at those specific locations",
        "A — Assess: Identify material nature-related risks and opportunities given your dependencies and impacts",
        "P — Prepare: Develop strategy, targets, and disclosure in response to findings",
      ]},
      { type: "h2", text: "The 14 core metrics" },
      { type: "p", text: "TNFD's September 2023 final framework includes 14 core global metrics and additional sector-specific metrics. The core metrics cover:" },
      { type: "ul", items: [
        "Land use: hectares of natural habitat in operational and sourcing footprint",
        "Freshwater use and pollution discharges: volumes and quality",
        "Greenhouse gas emissions: linked to TCFD",
        "Air pollutants: SOx, NOx, PM2.5 with nature-impact weighting",
        "Waste and pollution: volume and hazardous classification",
        "Biodiversity-sensitive area exposure: % of operations/sourcing in or near IUCN Key Biodiversity Areas",
        "Nature-related financial risks: assets exposed to physical, regulatory, and market nature risks",
      ]},
      { type: "h2", text: "Which sectors face highest nature-related risk?" },
      { type: "p", text: "Unlike climate, where the energy sector dominates, nature risk is spread much more broadly. The TNFD identifies eight sectors as priority high-nature-dependency sectors:" },
      { type: "table", headers: ["Sector", "Primary dependency", "Primary impact"], rows: [
        ["Agriculture & food", "Pollination, soil health, freshwater", "Land use change, fertiliser runoff"],
        ["Forestry & paper", "Forest ecosystems, water regulation", "Deforestation, biodiversity loss"],
        ["Mining", "Subsoil resources, land stability", "Habitat destruction, water pollution"],
        ["Oil & gas", "Land, water, air quality", "Pollution, habitat fragmentation"],
        ["Chemicals", "Freshwater, waste assimilation", "Pollution, toxic discharge"],
        ["Construction", "Land, aggregates, water", "Habitat loss, impervious surfaces"],
        ["Pharmaceuticals", "Genetic resources, traditional knowledge", "Biopiracy risk, over-harvesting"],
        ["Financial services", "All sectors via lending/investing", "Financing nature-harming activities"],
      ]},
      { type: "callout", variant: "info", title: "Early adopter status", text: "Over 320 organisations representing $6.5T in AUM had committed to TNFD-aligned disclosure by end 2024 — including HSBC, BNP Paribas, AXA, and Unilever. By 2026 adoption has accelerated significantly. Companies making voluntary disclosures now will have a significant advantage when mandatory requirements arrive, estimated for most EU companies by 2028 under CSRD Article 19." },
      { type: "h2", text: "What this means for ESG analysts in 2026" },
      { type: "p", text: "TNFD disclosures are still voluntary and patchy in 2026. But three things are shifting. First, institutional investors — particularly European asset managers — are beginning to ask about nature risk in their engagement programmes. Second, the Biodiversity COP30 process is likely to strengthen Target 15 compliance mechanisms. Third, courts in the Netherlands, UK, and France have begun accepting biodiversity damage as actionable corporate negligence." },
      { type: "p", text: "The practical implication: agriculture, food, mining, and construction companies with material operations in biodiversity-sensitive areas face emerging regulatory and litigation risk that current ESG scores systematically underweight. Analysing TNFD-aligned disclosures — or the absence of them — is becoming a source of alpha." },
    ],
  },
  // ─── 6 ───────────────────────────────────────────────────────────────────
  {
    slug: "esg-ratings-backlash",
    category: "Opinion",
    categoryColor: "bg-amber-100 text-amber-700",
    title: "The ESG Backlash: What the Performance Data Actually Shows",
    excerpt: "ESG investing is under sustained political attack in the US — over 40 states have introduced anti-ESG legislation. But what does the actual performance data show? We separate the political narrative from the empirical evidence on ESG returns, risk, and regulatory trajectory.",
    readTime: "9 min read",
    publishedDate: "April 2026",
    author: "OpenESG Research Team",
    authorRole: "Market Intelligence",
    coverGradient: "from-amber-600 to-orange-800",
    relatedSlugs: ["esg-ratings-divergence-2026", "water-risk-underpriced"],
    blocks: [
      { type: "h2", text: "What is actually happening" },
      { type: "p", text: "Since 2022, the US has seen a sustained political campaign against ESG investing. Over 40 states have introduced anti-ESG legislation. At least 19 states have restricted or divested public pension funds from ESG-focused managers. The US House passed legislation attempting to restrict the SEC's climate disclosure rules. Several major asset managers — including BlackRock — have publicly distanced themselves from the 'ESG' label while retaining the underlying strategies." },
      { type: "p", text: "The political argument has two main strands: first, that ESG investing is ideologically motivated and produces inferior returns (the fiduciary argument); second, that large asset managers using ESG to influence corporate behaviour constitutes an inappropriate exercise of economic and political power (the anti-concentration argument). These are distinct claims with different levels of empirical support." },
      { type: "callout", variant: "info", title: "The European trajectory is opposite", text: "While the US is experiencing an anti-ESG backlash, the EU has been tightening ESG requirements through CSRD, SFDR updates, the EU Taxonomy, and the Corporate Sustainability Due Diligence Directive. For global asset managers, this creates simultaneous pressure from opposite directions." },
      { type: "h2", text: "Testing the fiduciary argument" },
      { type: "p", text: "The claim that ESG investing produces inferior risk-adjusted returns is the empirically testable part of the backlash. The evidence is genuinely mixed — and depends significantly on the time period and ESG strategy analysed." },
      { type: "table", headers: ["Finding", "Source", "Period"], rows: [
        ["ESG funds underperformed value indices by 3.5% p.a.", "Morningstar, 2022 analysis", "2021–2022 (energy outperformance)"],
        ["ESG integration reduced portfolio volatility by 0.8%", "MSCI Research", "2012–2022"],
        ["High ESG scores predicted lower cost of capital", "Harvard Business School", "2015–2022"],
        ["ESG scores did not predict abnormal returns", "Journal of Finance meta-analysis", "2000–2021"],
        ["Climate risk exposure predicted underperformance", "BlackRock Investment Institute", "2019–2023"],
      ]},
      { type: "p", text: "The honest summary: ESG integration — meaning the systematic consideration of ESG factors in investment analysis — has a credible evidence base as a risk management tool. ESG as a marketing category — buying 'sustainable' funds with premium fees — has a weaker record. The backlash has mostly targeted the latter while rhetorically attacking the former." },
      { type: "h2", text: "The naming retreat" },
      { type: "p", text: "One of the most visible effects of the political pressure is the rebranding of ESG by major institutions. BlackRock's Larry Fink no longer uses the word 'ESG' in his annual letter, replacing it with 'energy pragmatism' and 'transition investing.' Goldman Sachs merged its ESG function into a broader 'sustainable investing' group. State Street announced reduced emphasis on ESG proxy voting." },
      { type: "p", text: "But look beyond the labels. BlackRock still manages $550 billion in sustainable investment assets. MSCI's ESG data business grew revenue 20% in 2024. The Principles for Responsible Investment gained 800 new signatories in 2024. The work is continuing under different names." },
      { type: "callout", variant: "tip", title: "What this means for investors", text: "The ESG backlash has created a pricing opportunity. Companies with genuinely strong sustainability credentials may be underpriced in markets where retail ESG fund outflows have depressed prices. Meanwhile, the regulatory trajectory in Europe continues to reward ESG leaders. Institutional investors with long time horizons and global mandates can arbitrage the political vs fundamental divergence." },
      { type: "h2", text: "What is actually at risk" },
      { type: "p", text: "The most legitimate concern in the backlash is not about returns — it is about concentration of power. When the three largest asset managers (BlackRock, Vanguard, State Street) collectively own 20–25% of every S&P 500 company and coordinate voting on climate and social issues, that represents a novel form of corporate governance power that has outpaced regulatory frameworks." },
      { type: "p", text: "This is a real governance question worth taking seriously — regardless of whether you support or oppose ESG policies. The policy response, however, has been almost entirely captured by short-term political interests rather than thoughtful institutional design. Anti-ESG state laws that prevent pension fund managers from considering climate risk — a material financial factor — are not protecting beneficiaries. They are protecting the short-term interests of fossil fuel producers." },
      { type: "h2", text: "Our view" },
      { type: "p", text: "ESG as a label is weakening under political pressure in the US. ESG as a practice — integrating environmental, social, and governance factors into investment analysis and corporate management — is growing in sophistication and regulatory backing globally. The analysts and investors who understand the difference will be better positioned than those who either dismiss the political pressure or accept its framing." },
    ],
  },
  // ─── 7 ───────────────────────────────────────────────────────────────────
  {
    slug: "water-risk-underpriced",
    category: "Research",
    categoryColor: "bg-violet-100 text-violet-700",
    title: "Water Risk in ESG Analysis: The Most Underpriced Material Factor",
    excerpt: "Carbon gets the headlines. Water gets the disruptions. Semiconductor fabs shutting down, food companies writing off crop failures, insurers retreating from coastal markets — water risk is already financially material and chronically underweighted in ESG scores.",
    readTime: "11 min read",
    publishedDate: "February 2026",
    author: "OpenESG Research Team",
    authorRole: "ESG Research",
    coverGradient: "from-cyan-600 to-blue-800",
    relatedSlugs: ["tnfd-nature-framework", "carbon-credits-demystified"],
    blocks: [
      { type: "h2", text: "Why water risk is different from climate risk" },
      { type: "p", text: "Climate change is a global commons problem. Water risk is hyper-local. A semiconductor manufacturer in drought-stricken Arizona faces acute operational risk today. The same company's factory in Scotland faces minimal water risk. This geographic specificity makes water risk genuinely hard to assess from standard ESG metrics — and means that company-level disclosures that aggregate global water use obscure where the real risk lies." },
      { type: "p", text: "The World Resources Institute's Aqueduct tool maps physical water stress at a watershed level for over 260,000 basins globally. Companies that overlay their facility footprint onto this map often discover that a disproportionate share of their production sits in high-stress basins. That is where the risk analysis should start." },
      { type: "callout", variant: "key", title: "The materiality threshold", text: "CDP data shows that companies with material water risk reported $301 billion in water-related financial impacts in 2023 — a 47% increase from 2022. Industries with the highest reported water risk include agriculture (44% of incidents), utilities (18%), materials (16%), and technology hardware (12%)." },
      { type: "h2", text: "Three types of water risk" },
      { type: "h3", text: "1. Physical risk — too little or too much water" },
      { type: "p", text: "Water scarcity is the most discussed: droughts reducing available fresh water for industrial and agricultural use. But flooding is equally material for many industries — data centres, manufacturing plants, and logistics infrastructure face increasing disruption from extreme precipitation events, which are becoming more frequent as the hydrological cycle intensifies under climate change." },
      { type: "h3", text: "2. Regulatory risk — water pricing and permit withdrawal" },
      { type: "p", text: "In many jurisdictions, water is dramatically underpriced relative to its scarcity. As aquifers deplete and dam capacity falls, governments are being forced to increase water prices and restrict industrial permits. California's Sustainable Groundwater Management Act (SGMA) has begun curtailing agricultural water rights that have been in place for decades — creating stranded asset risk for land and infrastructure that assumed free water access." },
      { type: "h3", text: "3. Reputational risk — social licence to operate" },
      { type: "p", text: "Mining, beverage, and semiconductor companies operating in water-stressed regions face growing community opposition when they compete with local populations for scarce fresh water. Coca-Cola's India water controversies in the 2000s, Nestlé's California groundwater extraction during the drought, and lithium mining's water demands in the Atacama are all examples of reputational risk that became operational risk through licence revocation and supply chain disruption." },
      { type: "h2", text: "Sector-by-sector exposure" },
      { type: "table", headers: ["Sector", "Primary risk type", "Key metric to watch"], rows: [
        ["Semiconductor / tech hardware", "Physical scarcity", "Fab locations vs Aqueduct stress score"],
        ["Agricultural inputs / food", "Physical scarcity + regulatory", "Sourcing basin water stress, rainfed vs irrigated %"],
        ["Utilities (thermal power)", "Physical + regulatory", "Cooling water withdrawal in stressed basins"],
        ["Beverages & bottled water", "Reputational + regulatory", "Local community impact, bottling plant water ratios"],
        ["Mining (lithium, copper)", "All three types", "Mine location, tailings water management"],
        ["Pharma / biotech", "Quality (contamination)", "Discharge monitoring, regulatory violations"],
        ["Real estate", "Flooding (too much water)", "Property exposure to 100-year floodplain changes"],
      ]},
      { type: "h2", text: "What good water disclosure looks like" },
      { type: "p", text: "CDP's Water questionnaire is the most comprehensive disclosure framework for corporate water risk. It requires companies to disclose water withdrawal by source and quality, water consumption, wastewater discharge, risk identification at the site level, targets, and business impacts already experienced." },
      { type: "p", text: "Only about 30% of Fortune 500 companies disclose to CDP Water. Of those, approximately half disclose at a site-level rather than just aggregate company-level. Site-level disclosure is the only way to assess actual basin-level risk — company aggregates are nearly useless for risk assessment." },
      { type: "checklist", title: "Water risk assessment checklist", items: [
        "Does the company disclose to CDP Water Security questionnaire?",
        "Are withdrawals disclosed by site/basin, not just company total?",
        "Map key facilities against WRI Aqueduct stress scores",
        "Are water targets absolute (volume) or intensity-based?",
        "Has the company experienced water-related production disruptions in past 3 years?",
        "What is the regulatory trend in key operating jurisdictions on water pricing?",
        "Does the company assess supplier water risk in agricultural/mining supply chains?",
        "Is water covered in the company's TCFD climate physical risk assessment?",
      ]},
      { type: "callout", variant: "info", title: "The insurance signal", text: "The insurance industry is the forward-looking market for physical risk. Swiss Re and Munich Re's pullback from insuring assets in flood-prone and drought-stressed regions is a real-time price signal about physical water risk. Companies whose key assets are becoming uninsurable at reasonable rates face material balance sheet risk that current ESG scores do not adequately capture." },
    ],
  },
  // ─── 8 ───────────────────────────────────────────────────────────────────
  {
    slug: "social-washing-beyond-greenwashing",
    category: "Due Diligence",
    categoryColor: "bg-amber-100 text-amber-700",
    title: "Social Washing in ESG: How to Detect False Social Sustainability Claims",
    excerpt: "Environmental greenwashing gets the headlines. Social washing — exaggerated or false claims about worker welfare, diversity, and community impact — is harder to detect, more common, and increasingly subject to regulatory enforcement under CSDDD, Germany's Supply Chain Act, and the UK Modern Slavery Act.",
    readTime: "10 min read",
    publishedDate: "January 2026",
    author: "OpenESG Research Team",
    authorRole: "ESG Due Diligence",
    coverGradient: "from-rose-600 to-pink-800",
    relatedSlugs: ["how-to-read-sustainability-report", "esg-ratings-divergence-2026"],
    blocks: [
      { type: "h2", text: "Why the 'S' is harder to verify than the 'E'" },
      { type: "p", text: "Environmental data — tonnes of CO₂, kilowatt-hours of energy, cubic metres of water — is physical and measurable. Social data — worker wellbeing, community impact, supply chain labour conditions — is often subjective, jurisdiction-specific, and fundamentally harder to verify from outside the organisation. This asymmetry means the 'S' pillar has historically received less rigorous ESG scrutiny despite being equally material." },
      { type: "p", text: "The regulatory response is accelerating. The EU Corporate Sustainability Due Diligence Directive (CSDDD), Germany's Supply Chain Act (LkSG), France's Duty of Vigilance law, and the UK Modern Slavery Act all impose legal obligations on large companies to identify and address human rights and labour violations in their supply chains. Social washing is no longer a reputational issue — it is becoming a legal one." },
      { type: "callout", variant: "warning", title: "Recent enforcement actions", text: "H&M faced a Swedish consumer authority investigation in 2022 for misleading sustainability claims about its Conscious Collection. Boohoo was dropped by major institutional investors after a Sunday Times investigation into Leicester factory labour conditions. Volkswagen's Xinjiang supplier controversy cost it an ESG premium and triggered US Uyghur Forced Labor Prevention Act scrutiny. Social washing enforcement is arriving." },
      { type: "h2", text: "The seven patterns of social washing" },
      { type: "h3", text: "1. Metric cherry-picking" },
      { type: "p", text: "Highlighting a positive social metric while concealing an equally relevant negative one. Example: promoting the percentage of women in senior management globally while burying the gender pay gap data or suppressing regional breakdowns where performance is poor." },
      { type: "h3", text: "2. Supply chain blindspot" },
      { type: "p", text: "Making strong statements about own-employee welfare while having no visibility into Tier 2 and 3 supplier labour conditions. The UK Modern Slavery Act disclosures of many major retailers amount to 'we sent suppliers a questionnaire' — not due diligence." },
      { type: "h3", text: "3. Absolute vs relative confusion" },
      { type: "p", text: "Claiming social progress using relative improvements from a low base. '50% improvement in workplace injury rates' sounds impressive until you learn the baseline was 40 incidents per 100 workers — still 4x the industry average after the improvement." },
      { type: "h3", text: "4. Initiative inflation" },
      { type: "p", text: "Announcing programmes, partnerships, and pledges in place of outcomes. A company might have 12 social initiatives and a 'Diversity Director' while showing zero measurable improvement in workforce demographic representation over five years." },
      { type: "h3", text: "5. Self-certification without audit" },
      { type: "p", text: "Publishing social code of conduct scores from supplier self-assessments presented as though they were independent audits. The garment industry's reliance on supplier self-certification has been repeatedly shown to be inadequate — the Rana Plaza factory that collapsed in 2013 had passed supplier audits months before." },
      { type: "h3", text: "6. Proxy metric substitution" },
      { type: "p", text: "Measuring something that is easy to count rather than what matters. 'Employee satisfaction survey score' tells you about the experience of current employees who have not left. It tells you nothing about why attrition is high, who is leaving, or what the experience is like for marginalised groups." },
      { type: "h3", text: "7. Regulatory arbitrage" },
      { type: "p", text: "Applying high labour standards in home markets while explicitly or implicitly accepting lower standards in jurisdictions with weaker enforcement. Companies that publish strong labour commitments in European markets while sourcing from suppliers in jurisdictions with documented forced labour or child labour issues fall into this category." },
      { type: "h2", text: "How to detect social washing" },
      { type: "p", text: "The tools are different from greenwashing detection, which can often rely on quantitative data. Social washing detection requires triangulating across sources." },
      { type: "ul", items: [
        "Worker voice: Glassdoor, Indeed, Blind, and equivalent platforms aggregate anonymous employee feedback that often contradicts corporate 'great place to work' claims",
        "NGO and investigative journalism: Organisations like Business & Human Rights Resource Centre, Clean Clothes Campaign, and Know The Chain track supply chain violations that rarely appear in company disclosures",
        "Regulatory enforcement: OSHA violation records (US), HSE enforcement actions (UK), and equivalent agencies in other markets provide observable data on safety performance",
        "Litigation data: Worker compensation claims, employment discrimination cases, and class actions are public records that pre-date corporate disclosure",
        "Supplier audit reports: Some companies now publish actual audit findings, not just pass/fail scores — these are significantly more informative",
        "Satellite and imagery data: Farms, factories, and facilities can be cross-referenced against known labour-risk supply chain databases",
      ]},
      { type: "checklist", title: "Social washing detection checklist", items: [
        "Are absolute numbers disclosed, not just percentages or indices?",
        "Does supply chain due diligence extend to Tier 2 suppliers or only direct (Tier 1)?",
        "Are social targets time-bound with interim milestones?",
        "Is workforce data broken down by region, gender, and ethnicity — or just global aggregate?",
        "Are third-party audits or certifications used (Fair Trade, SA8000, B Corp, Fair Labor Association)?",
        "Cross-reference Glassdoor/Indeed ratings with published employee satisfaction claims",
        "Check OSHA/HSE records for safety violations in past 3 years",
        "Search NGO databases for supply chain violations",
        "Check for Modern Slavery Act disclosures and whether they describe actual due diligence",
        "Review litigation history for employment discrimination or wage theft class actions",
      ]},
      { type: "callout", variant: "key", title: "Where ESG scoring falls short", text: "Most ESG rating providers rely heavily on corporate self-disclosure for social metrics. This creates a systematic bias toward companies that have invested in disclosure teams and communications infrastructure — not necessarily companies with better underlying social performance. The 'S' score gap between disclosure quality and actual social impact is wider than for any other ESG dimension." },
    ],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((b) => b.slug === slug);
}
